### ISSUE TITLE
Check exotic characters on Windows

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/native_messenger#16]
https://github.com/tridactyl/tridactyl/issues/876

and

https://github.com/tridactyl/tridactyl/issues/878

I'm assuming that nothing will have changed but it would be nice to know for certain.

Pinging @Rummskartoffel as our resident long suffering Windows user

**Comment by Rummskartoffel** [comment]
Cannot reproduce either on the new messenger. Don't ask me why, because I have no idea 🤷‍♂️
