### ISSUE TITLE
Very high CPU consumption by WMI due to nativemessenger on Windows 10

### ISSUE THREAD

**Issue by DhruvaSambrani** [tridactyl/native_messenger#40]
Tridactyl version: v1.21.0
Native version: v0.2.5
Waterfox: G3.1.1 (64-bit)
Windows 10

## Steps to repro
1. install native
2. close and open waterfox
3. Open Task Manager and see 40% CPU usage by WMI
4. Make scrambled eggs and bacon on your new Intel i7 stove 🙃 

## How do you know its native at fault?

When waterfox is closed, WMI goes back to using an occasional 1% CPU.
When waterfox is opened in safe mode, WMI behaves as usual
When waterfox is opened normally and tridactyl re-installed, WMI behaves as usual
When native is installed and waterfox opened, WMI shoots to 30-40%, fans run on full, the powergrid of the city fails and in 2 minutes time, an unhealthy breakfast is ready.

## Workaround

Uninstall native

PS: I have used very light language after looking at #2, please let me know if I need to edit it

**Comment by bovine3dom** [comment]
I assume WMI is this: https://en.m.wikipedia.org/wiki/Windows_Management_Instrumentation

Could you see if you have the same problem in Firefox with Tridactyl and native?

**Comment by DhruvaSambrani** [comment]
About WMI, yes it's that

I'll try and let you know about firefox behaviour

**Comment by DhruvaSambrani** [comment]
Firefox seems to be ok

**Comment by bovine3dom** [comment]
Do you see the same behaviour with the old python messenger and Waterfox? You can install it using this script: https://github.com/tridactyl/tridactyl/blob/master/native/win_install.ps1

If that works we should probably just try to detect Waterfox and fall back to that version.

**Comment by Rummskartoffel** [comment]
[Well, this is embarrassing.](https://github.com/tridactyl/tridactyl/blob/3078d5be5692f58109962fdeb3f20471bc8cc737/src/lib/native.ts#L481-L489) You should be able to find a PowerShell instance running that command somewhere among your processes. 

When I wrote that hack, I knew it'd break sometime somehow, and here we are. At the time, I hadn't considered the browser binary could be called anything else than `firefox.exe`. But when it is, that command loops endlessly, constantly creating and garbage-collecting expensive WMI objects. I'll see if I can write a temporary fix till I find a better solution.

**Comment by bovine3dom** [comment]
https://github.com/tridactyl/tridactyl/blob/191ac7c067754cd60a5787e05f891e424cc2099a/src/lib/config.ts#L919 FWIW we do already allow users to specify non-firefox binaries.

Can't we just use ppid of the native messenger? I thought we had written a Windows version of that

**Comment by Rummskartoffel** [comment]
That should work.

**Comment by Rummskartoffel** [comment]
Oh man, this is gonna get ugly after all. For future versions, it's easy enough – just `sendNativeMsg("ppid")`, then feed that into `Get-CimInstance -Query 'SELECT * FROM Win32_Process WHERE ProcessId = <ppid>`. But we still need some other way of figuring out the PPID on older Nim messenger versions, plus something different altogether for the Python version because the process tree looks different. I'd love to just throw backward compatibility out the window and leave it horribly broken on past versions, because that'd be way easier.

**Comment by bovine3dom** [comment]
> But we still need some other way of figuring out the PPID on older Nim messenger versions

We can retain the current behaviour for it. Almost no-one will use Waterfox, Windows _and_ an old but not very old native messenger.

> plus something different altogether for the Python version because the process tree looks different

What did we do before? Can't we just do that?

**Comment by Rummskartoffel** [comment]
If we keep the current behaviour, then we don't need to change anything for the Python version, either. I guess someone using Waterfox and the Python messenger is also not very likely.

**Comment by bovine3dom** [comment]
Well if it uses 40% of their CPU they probably won't be using it for long :laughing:

**Comment by Rummskartoffel** [comment]
I do really think Tridactyl really needs *some* way of getting users off old versions, or some other way of safely introducing breaking changes, because IMO already way too much code is just there for backward compatibility, and it's not going to get less.

**Comment by bovine3dom** [comment]
Fixing https://github.com/tridactyl/tridactyl/issues/614 would fix most of that.

But I've said that the Python messenger will stay supported for as long as it's feasible so I'd rather not do that. Is there any backwards-compat code that you particularly hate?

**Comment by Rummskartoffel** [comment]
I think my current unfavourite is probably the version-checking for `:updatenative` I wrote a few days ago, tridactyl/tridactyl@45ac1f10, though that's not because it's particularly terrible – I think it's okay for what it is –, but because I dislike the fact it had to be written at all.
And I don't think it's bad to provide backward compatibility, but I – probably somewhat irrationally – dislike code that achieves that.

**Comment by bovine3dom** [comment]
> And I don't think it's bad to provide backward compatibility, but I – probably somewhat irrationally – dislike code that achieves that

It adds branches to code that won't be tested or even used very often, so I see where you're coming from.

Our CI is stuck on the python version of the native messenger, though, so it might be more tested than you realise : )

**Comment by DhruvaSambrani** [comment]
I just noticed, there's a tridactyl variable(? setting?) called `browser`. Maybe that should be set when installing nativemessenger according to the actual browser? I don't really know if it is used, and I agree that actually finding the PID is a safer "no global variables" approach, but I was just letting you know if y'all had missed that?

**Comment by bovine3dom** [comment]
https://github.com/tridactyl/native_messenger/issues/40#issuecomment-787910364 I mentioned it in this thread :D

Thanks for pointing it out anyway : )

**Comment by Rummskartoffel** [comment]
tridactyl/tridactyl#3443 will fix this issue and make `ff_cmdline()` respect 'browser' on old messenger versions. It'd still need to be manually set, though.
