### ISSUE TITLE
Guiset regression on some systems

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/native_messenger#45]
Reported in https://github.com/tridactyl/tridactyl/issues/3418

There must be some subtle difference between how the two messengers read and write.

**Comment by Rummskartoffel** [comment]
Can repro on win8, native 0.3.3.

**Comment by Rummskartoffel** [comment]
Think I've got it. [`writePref` depends on `read` returning `""` when it fails](https://github.com/tridactyl/tridactyl/blob/bec8ec2dde139b2b5d98f77a4f7e99cca9e17560/src/lib/native.ts#L833-L835), but [`read` doesn't do that](https://github.com/tridactyl/native_messenger/blob/b96b9fd020fd12b04e9be7d99d2a86d88a83b87f/src/native_main.nim#L160-L167).
