### ISSUE TITLE
:saveas into directory doesn't work

### ISSUE THREAD

**Issue by jakanakaevangeli** [tridactyl/native_messenger#51]
To reproduce:
Make a directory called `~/Documents`.
In trydactyl, type `:saveas ~/Documents`.
An error is signalled that the downloaded file could not be moved to
'~/Documents'.

However, documentation of :saveas says that the destination can be a directory
and the downloaded file will be saved into it.

**Comment by jakanakaevangeli** [comment]
Another similar issue is `:saveas ~/Downloads`, where ~/Downloads is set as the
default download location. The native messenger will signal an error as it will
try to move the file onto itself.

On GNU/Linux, using the nim native messenger.

**Comment by bovine3dom** [comment]
I'm away at the moment, so it might take me a while to look into this. If it looks like I've forgotten about it please ping me :)

**Comment by Rummskartoffel** [comment]
Can reproduce on Windows. The native messenger appears to correctly receive the command, but `os.moveFile()` raises an OSError with the helpful message "Access is denied". Haven't yet tested what it says on Linux.
