### ISSUE TITLE
Support for OpenBSD & Nim 1.2.0 | or at least help to modify for Nim 1.2.0

### ISSUE THREAD

**Issue by anoduck** [tridactyl/native_messenger#55]
For several years, I have wished native_messenger was compatible with OpenBSD, and I had assumed that it was merely a limitation of knowledge that prevented this from happening. Recently, I was successful in setting up firefox to communicate with a different messenger application, so I figured I should resurrect my work on native_messenger and try again. 

Since the installation script installs native_messenger as an Executable Linux File (ELF), it would not be able to run on a native unix(bsd) system, which means it is going to have to be compiled. Nim 1.2.0 is available in the OpenBSD ports collection, and has been installed. Unfortunately, the minimum requirement to compile native_messenger appears to be Nim 1.4.2. Ignoring this fact, I attempted to compile anyway, and as you could guess, it failed. 

Frankly speaking, it is unpleasant having to download Nim 1.4.2, attempt to compile it, learn how to write code in Nim, troubleshoot all potential errors, possibly contact other developers to mitigate those encountered errors, maybe arrive at a resolution, and then attempt to compile Nim again. All just to then attempt to compile native_messenger again. So, I was wondering if there is anyway I could get some help to allow native_messenger to compile using Nim 1.2.0? The differences between 1.4.2 and 1.2.0 are possibly not too great. 

Right now, compilation with 1.2.0 is breaking on line 145 in native_main.nim, with a type mismatch error. I will post the full output below to help troubleshoot the error. 

```bash
        ... /home/user/native_messenger/src/native_main.nim(145, 32) Error: type mismatch: got <Process>
        ... but expected one of: 
        ... iterator lines(f: File): TaintedString
        ...   first type mismatch at position: 1
        ...   required type for f: File
        ...   but expression 'process' is of type: Process
        ... iterator lines(filename: string): TaintedString
        ...   first type mismatch at position: 1
        ...   required type for filename: string
        ...   but expression 'process' is of type: Process
        ... iterator lines(s: Stream): TaintedString
        ...   first type mismatch at position: 1
        ...   required type for s: Stream
        ...   but expression 'process' is of type: Process
        ... expression: lines(process)
```

Thank you for your time and investment.

**Comment by Rummskartoffel** [comment]
#56 should do it, unless there are other issues that are specific to BSD.

**Comment by anoduck** [comment]
Eureka! Like butter, absolutely like butter. Thanks.

**Comment by anoduck** [comment]
After modifying the installation script to copy and not curl, and adding execution permissions to unveil.main, my mind was completely blown when I saw:
```text
# Native messenger is correctly installed, version 0.3.6
```
Bosanova! Super!
