### ISSUE TITLE
Would native be able to allow commands during page load?

### ISSUE THREAD

**Issue by sandrock** [tridactyl/native_messenger#67]
Tridactyl is not active when a page takes time to load.

Say you have a window with dozens of inative tabs. Doing JJJJJJ or KKKKK does not allow to change tab in a smooth way, because each tab may need to reload. 

Can tridactyl native fix this kind of limitation?

Side-note: I am using the [auto tab discard](https://addons.mozilla.org/en-US/firefox/addon/auto-tab-discard/) extension to cope with the hundreds of tabs I have. This extension makes a lot of tab go to sleep.

**Comment by bovine3dom** [comment]
Thanks for filing this!

Short answer: no

Long answer:

1. if we rewrote the native messenger to be persistent we could allow the native messenger to send unsolicited messages to Tridactyl
2. we could transmit the current mode / whether Tridactyl was running in the tab to the native messenger each time it changed
3. the native messenger could then reload e.g. `xkeysnail` to change the bindings
4. `xkeysnail` could then convert key sequences to messages to the native messenger
5. the native messenger would then transmit messages to Tridactyl running in the browser to perform actions

but each of those steps is a lot of work. and at the end of it there are no guarantees on latency. It could be a man-month of work+ only to find out that it is too slow to use in practice.

I think a better approach would be to hack onto the `Keyboard API` in Firefox to accept keysequences / quickly disable/enable sets of keybinds (for mode switching) / accept binds that don't have modifiers.

---

I can suggest some workarounds for you:

- use Ctrl-Tab/Tab default binds to switch tabs
- make a `:bind --mode=browser` bind to `:tabnext`/prev - these binds work anywhere but have to be key+modifier and have not be reserved by Firefox - the only way to find out is to try and see if the bind actually works
- `:reloaddead` in Tridactyl reloads all tabs that Tridactyl is unresponsive in - usually the discarded ones


Closing this issue in favour of https://github.com/tridactyl/tridactyl/issues/780 which although it doesn't say it explicitly covers much of the same ground :)

**Comment by sandrock** [comment]
Thanks for the complete answer.  

- Yeah, I fallback to Ctrl+Tab when that occurs.   
- I also try to use the "b" command instead of J/K when I know I will hit dead tabs
- Reloading all dead tabs would have dire memory consequences; I won't go for that. 
- And about browser-mode key bindings:

When I do:

```
bind --mode=browser J tabprev
bind --mode=browser K tabnext
```

I get:

> # controller in excmd: Error: Type error for parameter detail (Error processing shortcut: Error: Value "K" must consist of either a combination of one or two modifiers, including a mandatory primary modifier and a key, separated by '+', or a media key. For details see: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/commands#Key_combinations) for commands.update.

**Comment by bovine3dom** [comment]
Yeah, that's expected - `--mode=browser` binds can only be key+modifier, e.g. `Ctrl+.`.

When I said

> I think a better approach would be to hack onto the `Keyboard API` in Firefox to accept keysequences / quickly disable/enable sets of keybinds (for mode switching) / accept binds that don't have modifiers.

I was talking about patching Firefox to remove that limitation. In the distant past we started our own approach here - https://github.com/tridactyl/keyboard-api - but we should probably throw that out and instead modify the existing API, then beg Mozilla to merge it.
