### ISSUE TITLE
Can I access the native messenger from js file?

### ISSUE THREAD

**Issue by shth** [tridactyl/native_messenger#75]
I want to add a script that will run on certain urls using autocmds. And I want it to execute some commands in the terminal using native messenger. Is that possible? 

Example:
```
autocmd DocStart gitlab\.com js -r example.js
```

```js
// example.js
// execute some command in terminal with some parameters, e.g. echo "..."
```

**Comment by bovine3dom** [comment]
Sorry, I don't know how I missed this issue for so long.

Yeah, you should be able to use `tri.excmd.exclaim_quiet("commands go here")` which is equivalent to `:!s commands go here` interactively
